<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>false</UseWPF>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <CreateCipx>true</CreateCipx>
    <LangVersion>latest</LangVersion>
    <AssemblyName>Voyage.EarthquakeWarning</AssemblyName>
    <RootNamespace>Voyage.EarthquakeWarning</RootNamespace>
    <Platforms>AnyCPU</Platforms>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="**\*.cs" Exclude="obj\**;bin\**">
      <LogicalName>Src.%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClassIsland.PluginSdk" Version="2.1.0.1">
      <ExcludeAssets>runtime; native</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="NAudio" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="manifest.yml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
      <PublishFolderType>Resource</PublishFolderType>
    </None>
    <None Update="README.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
      <PublishFolderType>Resource</PublishFolderType>
    </None>
    <None Update="icon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
      <PublishFolderType>Resource</PublishFolderType>
    </None>
    <None Update="Assets\Audio\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
      <PublishFolderType>Resource</PublishFolderType>
    </None>
    <None Update="Assets\Images\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
      <PublishFolderType>Resource</PublishFolderType>
    </None>
  </ItemGroup>
</Project>
